apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democrm
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/raziel-93/gitops-configuration.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
