Global:
  replicaCount: 2
  name: todoo
  image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/raziel-jenkins
  tag: 2.1.42
deployment:
  port: 7070
  volumeEnabled: true
  resourceLimits:
    memory: 128Mi
    cpu: 250m
  resourceRequests:
    memory: 128Mi
    cpu: 250m
mongoSecret:
  name: mongov1
  url: mongodb://root:password@todoo-mongodb-headless:27017/?replicaSet=rs0
env:
- name: MONGO_URL
  key: url
service_todoo:
  port: 80
  name: todoo-service
ingress:
  clusterIssuer: cryt-crm
  ingressClassName: nginx
  host: razieldemocrm.hopto.org
  secretName: democrm-cert
cluster_issuer:
  name: cryt-crm
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  email: afandaev93@gmail.com
  privateKeySecretRef: cryt-crm
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
mongodb:
  commonLabels:
    app: mongo
  architecture: replicaset
  auth:
    rootUser: root
    rootPassword: password
  replicaCount: 3
  service.nameOverride: mongodb-service
  persistence.storageClass: standard
  persistence.size: 1Gi
