Global:
  replicaCount: 2
  name: democrm
  image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/raziel-jenkins
  tag: 2.1.11
deployment:
  port: 7070
  volumeName: config-volume
  mountPath: /app/.env
  subPath: .env
  volumeEnabled: true
  resourceLimits:
    memory: 128Mi
    cpu: 250m
  resourceRequests:
    memory: 128Mi
    cpu: 250m
mongoSecret:
  name: mongov1
  username: root
  password: password
  db_service: democrm-mongodb-headless
env:
- name: MONGO_INITDB_ROOT_USERNAME
  key: mongo-user
- name: MONGO_INITDB_ROOT_PASSWORD
  key: mongo-password
- name: MONGO_DB_SERVICE
  key: service_name
config:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_DB_SERVICE: democrm-mongodb-headless
service_democrm:
  port: 80
  name: democrm-service
ingress:
  clusterIssuer: cryt-crm
  ingressClassName: nginx
  host: razieldemocrm.hopto.org
  secretName: democrm-cert
cluster_issuer:
  name: cryt-crm
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  email: afandaev93@gmail.com
  privateKeySecretRef: cryt-crm
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
mongodb:
  commonLabels:
    app: mongo
  architecture: replicaset
  auth:
    rootUser: root
    rootPassword: password
  replicaCount: 1
  service.nameOverride: mongodb-service
  persistence.storageClass: standard
  persistence.size: 1Gi
