apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cluster_issuer.name }}
spec:
  acme:
    server: {{ .Values.cluster_issuer.acmeServer }}
    email: {{ .Values.cluster_issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.cluster_issuer.privateKeySecretRef }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.ingressClassName}}
