apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Global.name }}
  labels:
    app: {{ .Values.Global.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.Global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.Global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Global.name }}
    spec:
      containers:
      - name: {{ .Values.Global.name }}
        image: "{{ printf "%s:%s" .Values.Global.image .Values.Global.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.port }}
        resources:
          limits: {{- toYaml .Values.deployment.resourceLimits | nindent 12 }}
          requests: {{- toYaml .Values.deployment.resourceRequests | nindent 12 }}
        env:
        {{- range .Values.env }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: "{{ $.Values.mongoSecret.name }}-secret"
                key: {{ .key }}
        {{- end }}


        