apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.mongoSecret.name }}-secret"
type: Opaque
data:
  mongo-user: {{ .Values.mongoSecret.username | b64enc | quote }}
  mongo-password: {{ .Values.mongoSecret.password | b64enc | quote }}
  service_name : {{ .Values.mongoSecret.db_service | b64enc | quote }}
  url: {{ .Values.mongoSecret.url | b64enc | quote }}
